export default {
    "sweeps-0": "SpoopySweepsN.ogg",
    "boss-1": "BossFightV3Heim.ogg",
    "ambient-0": "ambientfinal(typ)remixedMasteredN.ogg",
    "throneroom": "ThroneroomN.ogg",
    "dumdum": "dumdumdummixedMasteredN.ogg",
    "arrow": "XbowV5.wav",
    "wind": "VindloopFinal.wav",
    "rain": "rainlong.ogg",
    "playerFall": "XbowV5SN.ogg",
    "playerFall2": "Movement2Heim.ogg",
    "playerFall3": "UH.wav",
    "playerStep1": "gustavSteg1.wav",
    "playerStep2": "gustavSteg2.wav",
    "playerStep3": "gustavSteg3.wav",
    "playerStep4": "Movement1HeimN.ogg",
    "playerStep5": "Movement2HeimN.ogg",
    "playerStep6": "Movement3HeimN.ogg",
    "bossStep-1": "BigStep1N.ogg",
    "bossStep-2": "BigStep2N.ogg",
    "bossStep-3": "BigStep3N.ogg",
    "bossScream": "Boss Scream.ogg",
    "bossLaser": "laserLUL.ogg",
    "genericImpact": "Impact.ogg",
    "playerTeleport": "SLASHv1N.ogg",
}